[package]
name = "mrml"
description = "Rust implementation of MJML renderer"
keywords = ["email", "mjml"]
version = "0.0.1"
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
license = "TBD"
edition = "2018"

include = [
  "src/*",
  "Cargo.toml",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
regex = "1"
roxmltree = "0.11"

[dev-dependencies]
difference = "2.0"
