[package]
name = "mrml"
description = "Rust implementation of MJML renderer"
keywords = ["email", "mjml"]
version = "0.2.0"
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
license-file = "license.md"
edition = "2018"
readme = "readme.md"

include = [
  "src/*",
  "Cargo.toml",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
circle-ci = { repository = "jdrouet/mrml" }
codecov = { repository = "jdrouet/mrml" }

[dependencies]
lazy_static = "1.4"
log = "0.4"
rand = { default-features = false, features = ["std"], version = "0.7" }
regex = "1"
roxmltree = "0.11"
xmlparser = "0.13"

[dev-dependencies]
criterion = "0.3"
difference = "2.0"

[[bench]]
name = "basic"
harness = false

[[bench]]
name = "template"
harness = false
