version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: jdrouet/rust-nightly:buster-slim
    steps:
      - checkout
      - run: cargo install grcov
      - run:
          command: cargo build --verbose $CARGO_OPTIONS
          environment:
            CARGO_INCREMENTAL: "0"
            RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
            RUSTDOCFLAGS: "-Cpanic=abort"
      - run:
          command: cargo test --verbose $CARGO_OPTIONS
          environment:
            CARGO_INCREMENTAL: "0"
            RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
            RUSTDOCFLAGS: "-Cpanic=abort"
      - run: grcov ./target/debug -t coveralls -s . --token $CODECOV_TOKEN > coveralls.json
      - run: bash <(curl -s https://codecov.io/bash) -f coveralls.json
