version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
    steps:
      - checkout
      - run:
          command: bash script/run-coverage.sh
          environment:
            BASIC_DIFF: "true"
      - run: bash script/push-coverage.sh
