version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - bench

jobs:
  test:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
    steps:
      - checkout
      - run: rustfmt --check src/{**/,}*.rs
      - run: cargo clippy -- -D warnings
      - run:
          command: bash script/run-coverage.sh
          environment:
            BASIC_DIFF: "true"
      - run: bash script/push-coverage.sh

  bench:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
    steps:
      - checkout
      - restore_cache:
          keys: bench-master
      - run: cargo bench
      - save_cache:
          key: "bench-{{ .Branch }}"
          paths:
            - target/criterion
