on:
  push:
    tags:        
      - 'v*'

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.repository == 'jolimail/mrml-core'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

      - name: Notify mastodon
        uses: cbrgm/mastodon-github-action@v1
        with:
          message: |
            👋 Hey! I just released a new version of mrml!
            Take a look at it, it's made in #rustlang, it's #opensource and it's a #freesoftware!"
            https://github.com/jolimail/mrml-core
          visibility: "public"
        env:
          MASTODON_URL: ${{ secrets.MASTODON_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
